### PR TITLE
MK3 fan nozzle fixed

### PR DESCRIPTION
**Pull request by stahlfabrik**
The MK3 fan nozzle model has multiple problems

a) the text "HOT!2" is extruded wrong: it reaches to the inside of the fan nozzle which degrades air flow
b) the cutout for the fan is too big. Air can easily escape. I reduced it by 0.5 mm. It could be even a little smaller

Since the production part's text does NOT reach INSIDE - I wonder why the production version is not the same as is the GitHub version? 

I wonder how the other parts differ from production to open source versions (Please Prusa Research, make sure to publish up to dates files)

Best regards

### CODE REVIEW

**Comment by stahlfabrik** [comment]
Hello Prusa Research - any feedback regarding the faulty part here on GitHub? Are there other differences between production parts and the public parts that the owners of a Prusa Printer can reprint? Please make sure to keep refinements flowing into the publicly released parts. Your enthusiastic community (who want to rebuild their printer in other colors etc.) are very, very thankful for that!

**Comment by tracernz** [comment]
AFAICT no PRs have ever been merged into this repo. :confused:

**Comment by prusa3d-bb** [comment]
Hello,

I will forward this info to developers and they will check and update it.

Regards


—
Bart Skonieczka

Customer Support


PRUSA Research

+420 222 263 718

+421 220 570 305

188/7a Partyzánská, 17000, Prague

shop.prusa3D.com

For simple troubleshooting, please use: http://help.prusa3d.com


Please rate our reply ...be generous :-)

--- original message ---
On Wed, Jun 20, 2018 at 09:28 am, <notifications@github.com> Michael Corcoran wrote:


AFAICT no PRs have ever been merged into this repo. 😕

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by stahlfabrik** [comment]
For me - it is not important that my PR gets merged. For me, it is important that the refinements that are surely performed in production on a routinely basis get released in a timely manner - especially important when the parts that have been released yet are faulty. If I want to reprint parts to make them nicer, stronger or a different color - I do not want to introduce bugs that long have been resolved in production. That seems so not in the spirit of "open source" IMHO.

EDIT: thank you Bart for your reply!

**Comment by prusa3d-bb** [comment]
Developers are already working on this.


—
Bart Skonieczka

Customer Support


PRUSA Research

+420 222 263 718

+421 220 570 305

188/7a Partyzánská, 17000, Prague

shop.prusa3D.com

For simple troubleshooting, please use: http://help.prusa3d.com


Please rate our reply ...be generous :-)

--- original message ---
On Wed, Jun 20, 2018 at 09:38 am, <notifications@github.com> Christoph Stahl wrote:


For me - it is not important that my PR gets merged. For me, it is important that the refinements that are surely performed in production on a routinely basis get released in a timely manner - especially important when the parts that have been released yet are faulty. If I want to reprint parts to make them nicer, stronger or a different color - I do not want to introduce bugs that long have been resolved in production. That seems so not in the spirit of "open source" IMHO.

—

You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by stahlfabrik** [comment]
The old fan nozzle is still unfixed

**Comment by stahlfabrik** [comment]
This nozzle design and is history

**Pull request closed without merging**
